### ISSUE TITLE
Latest versions

### ISSUE THREAD

**Issue by rashil2000** [julian-r/file-windows#18]
Hi @julian-r!

I'm planning to upgrade the `file` package in Scoop package manager. Currently it's stuck on a very old GnuWin32 build - https://github.com/ScoopInstaller/Main/blob/master/bucket/file.json

I'd like to ask if there's any plan to release the latest version of `file` (5.41)?

**Comment by julian-r** [comment]
yes, can do this the next days

**Comment by rashil2000** [comment]
I'd love to but I have no clue how any of this is done 😅

If I remember correctly there was a PR for this already - https://github.com/julian-r/file-windows/pull/15

**Comment by jonaski** [comment]
I have already upgraded to 5.41 n my repo here: https://github.com/jonaski/qt-msvc and can submit a PR here if you want.
But some patching for MSVC is necessary, see https://github.com/jonaski/qt-msvc/blob/e45b454c5146ac10b07546bcbe27953ddc224543/patches/file-1-fixes.patch
How would you like me to do that here? Is it OK to include the entire patches file source instead of using a submodule?

**Comment by julian-r** [comment]
@rashil2000 just released v5.44
